import { ArrowUpRight, ArrowDown, Phone, MapPin, Star, Wrench, Cog, Disc3, MoveVertical } from 'lucide-react';
const phone = 'tel:+554626040763';
const maps = 'https://www.google.com/maps/search/?api=1&query=Auto+Mec%C3%A2nica+Vans+Pato+Branco';
const services = [
  { name: 'Motores em geral', text: 'O coração do seu veículo merece atenção. Fale com a oficina sobre a manutenção do motor.', icon: Cog },
  { name: 'Suspensão', text: 'Ruídos ou mudanças no conforto ao dirigir? Consulte a oficina sobre o sistema de suspensão.', icon: MoveVertical },
  { name: 'Freios', text: 'Atenção a um dos sistemas mais importantes do veículo. Entre em contato para avaliar os freios.', icon: Disc3 },
];
export default function Home() {
  return <>
    <a className="skip" href="#conteudo">Ir para o conteúdo</a>
    <div className="topline"><div className="wrap"><span>PATO BRANCO · PARANÁ</span><a href={phone}>CONTATO DIRETO <span>(46) 2604-0763</span></a></div></div>
    <header className="header"><div className="wrap nav">
      <a className="brand" href="#inicio" aria-label="Auto Mecânica Vans, início"><span className="brand-symbol">V<span> /</span></span><span><strong>VANS</strong><small>AUTO MECÂNICA</small></span></a>
      <nav aria-label="Navegação principal"><a href="#sobre">A oficina</a><a href="#servicos">Serviços</a><a href="#avaliacoes">Avaliações</a><a href="#localizacao">Localização</a></nav>
      <a className="button nav-cta" href={phone}><Phone size={16}/> Falar com a oficina <ArrowUpRight size={17}/></a>
    </div></header>
    <main id="conteudo">
      <section className="hero" id="inicio"><div className="wrap">
        <div className="hero-top"><span className="eyebrow"><i/> LINHA LEVE & LINHA DIESEL</span><span className="hero-location">BORTOT / PATO BRANCO</span></div>
        <div className="hero-layout"><div className="hero-copy"><h1>MECÂNICA PARA<br/>QUEM PRECISA<br/><em>SEGUIR.</em></h1><p>Motores, suspensão e freios.<br/>Auto Mecânica Vans: cuidado com o seu veículo, aqui em Pato Branco.</p><div className="actions"><a className="button" href={phone}><Phone size={18}/> Falar com a oficina <ArrowUpRight size={18}/></a><a className="text-link" href={maps} target="_blank" rel="noopener noreferrer">Como chegar <ArrowUpRight size={18}/></a></div></div>
        <aside className="identity-panel" aria-label="Auto Mecânica Vans, motores, suspensão e freios"><div className="panel-top"><span>AUTO MECÂNICA</span><Wrench size={25}/></div><div className="vans-type">VANS<span>///</span></div><div className="panel-services"><span>MOTORES</span><span>SUSPENSÃO</span><span>FREIOS</span></div><div className="panel-bottom"><span>LINHA LEVE<br/><b>LINHA DIESEL</b></span><span className="panel-arrow">↗</span></div></aside></div>
        <div className="hero-bottom"><a href="#servicos">CONHEÇA OS SERVIÇOS <ArrowDown size={16}/></a><a className="rating-mini" href="#avaliacoes"><span><Star size={15} fill="currentColor"/> 5,0</span> 6 avaliações no Google <ArrowUpRight size={15}/></a></div>
      </div></section>
      <section id="sobre" className="section about"><div className="wrap about-grid"><div><span className="eyebrow dark-text">01 / A OFICINA</span><h2>DA ROTINA<br/>AO TRABALHO.<br/><span>O SEU VEÍCULO<br/>EM MOVIMENTO.</span></h2></div><div className="about-copy"><p className="lead">Uma oficina em Pato Branco para a manutenção da linha leve e da linha diesel.</p><p>A Auto Mecânica Vans está no bairro Bortot, na Rua Vereador Alberto Geron. Sua atuação reúne motores em geral, suspensão e freios.</p><p>Precisa de um serviço? Fale diretamente com a oficina, explique o que está acontecendo com o veículo e consulte a disponibilidade de atendimento.</p><div className="line-tags"><span>Linha leve</span><span>Linha diesel</span></div><a className="text-link dark-text" href="#contato">Entre em contato <ArrowUpRight size={20}/></a></div></div></section>
      <section id="servicos" className="section services"><div className="wrap"><div className="section-heading"><div><span className="eyebrow dark-text">02 / SERVIÇOS</span><h2>ATENÇÃO AO QUE<br/>MOVE VOCÊ.</h2></div><p>Mecânica para a linha leve e diesel.<br/>Consulte o atendimento para o seu veículo.</p></div><div className="service-grid">{services.map((service,i)=><article className="service" key={service.name}><div className="service-top"><service.icon size={34} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{service.name}</h3><p>{service.text}</p><a href={phone}>Consultar serviço <ArrowUpRight size={19}/></a></article>)}</div></div></section>
      <section id="avaliacoes" className="section reviews"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">03 / AVALIAÇÕES NO GOOGLE</span><h2>QUEM JÁ VEIO<br/>TEM O QUE DIZER.</h2></div><a className="rating-large" href={maps} target="_blank" rel="noopener noreferrer"><b>5,0<span>/5</span></b><span><span className="stars" aria-label="5 estrelas">★★★★★</span><small>6 avaliações no Google ↗</small></span></a></div><div className="review-grid">{[{name:'Chicão Bergamo',text:'Excelente atendimento, profissionalismo total!'},{name:'Conte',text:'Super recomendado'},{name:'Itamar Mondardo',text:'Excelente'}].map(review=><figure className="review" key={review.name}><span className="stars" aria-label="5 estrelas">★★★★★</span><blockquote>“{review.text}”</blockquote><figcaption><span className="review-initial" aria-hidden="true">{review.name[0]}</span><span>{review.name}<small>Avaliação no Google</small></span><span className="google-letter" aria-label="Google">G</span></figcaption></figure>)}</div><div className="review-source">Avaliações consultadas em setembro de 2026.<a href={maps} target="_blank" rel="noopener noreferrer">Ver no Google Maps <ArrowUpRight size={15}/></a></div></div></section>
      <section id="localizacao" className="section location"><div className="wrap"><div className="section-heading"><div><span className="eyebrow dark-text">04 / LOCALIZAÇÃO</span><h2>PERTINHO DE VOCÊ.<br/>AQUI NO BORTOT.</h2></div><a className="button dark-button" href={maps} target="_blank" rel="noopener noreferrer"><MapPin size={18}/> Traçar minha rota <ArrowUpRight size={18}/></a></div><div className="location-grid"><div className="address-card"><MapPin size={28}/><h3>Auto Mecânica Vans</h3><address>Rua Vereador Alberto Geron, 137<br/>Bortot · Pato Branco – PR<br/>CEP 85501-390</address><div className="address-details"><span>TELEFONE</span><a href={phone}>(46) 2604-0763</a><span>ATENDIMENTO</span><p>Consulte os horários e a disponibilidade por telefone.</p></div></div><iframe title="Localização da Auto Mecânica Vans no Google Maps" src="https://maps.google.com/maps?q=-26.2161213,-52.6793932&z=17&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></div></section>
      <section id="contato" className="contact"><div className="wrap contact-grid"><div><span className="eyebrow">05 / VAMOS CONVERSAR</span><h2>SEU PRÓXIMO<br/>PASSO É AQUI.</h2><p>Conte qual é o veículo e o serviço que você precisa.<br/>Fale diretamente com a Auto Mecânica Vans.</p></div><div className="contact-action"><span>TOQUE PARA LIGAR</span><a className="phone-big" href={phone}>(46) 2604-0763 <ArrowUpRight/></a><a className="button white-button" href={phone}><Phone size={18}/> Ligar para a oficina <ArrowUpRight size={18}/></a></div></div></section>
      <section className="request-section" id="solicitacao"><div className="wrap"><form id="whatsapp-request" className="request-form" data-whatsapp="" aria-labelledby="request-title">
        <div className="request-heading"><span className="eyebrow">ATENDIMENTO PELO WHATSAPP</span><h2 id="request-title">Conte o que seu carro precisa.</h2></div>
        <label htmlFor="request-name">Nome<input id="request-name" name="customer" autoComplete="name" placeholder="Seu nome" required maxLength={80}/></label>
        <div className="request-row"><label htmlFor="request-phone">Seu WhatsApp<input id="request-phone" name="phone" type="tel" autoComplete="tel" inputMode="tel" placeholder="(46) 99999-9999" required pattern="[+()0-9 .-]{10,20}" maxLength={20}/></label><label htmlFor="request-car">Veículo<input id="request-car" name="vehicle" placeholder="Modelo do carro" required maxLength={100}/></label></div>
        <label htmlFor="request-service">Serviço<select id="request-service" name="service" required defaultValue=""><option value="" disabled>Selecione</option><option>Motores em geral</option><option>Suspensão</option><option>Freios</option><option>Quero uma orientação</option></select></label>
        <label htmlFor="request-notes">Observação <span>(opcional)</span><textarea id="request-notes" name="notes" placeholder="Conte algum detalhe, se quiser." rows={4} maxLength={1000}/></label>
        <button className="button request-submit" id="prepare-request" type="button">Preparar mensagem para WhatsApp <ArrowUpRight size={19}/></button>
        <p className="request-note" id="request-status" role="status" aria-live="polite">Formulário para direcionamento ao WhatsApp da oficina. Nesta demonstração, nenhum dado é enviado; a ativação depende da confirmação do número.</p>
        <pre id="request-preview" className="request-preview" hidden/>
        <noscript><p>Ative o JavaScript para preparar a mensagem. Você também pode ligar para (46) 2604-0763.</p></noscript>
      </form></div></section>
    </main><footer><div className="wrap footer-main"><a className="brand" href="#inicio"><span className="brand-symbol">V<span> /</span></span><span><strong>VANS</strong><small>AUTO MECÂNICA</small></span></a><p>Motores em geral · Suspensão · Freios<br/>Linha leve e linha diesel</p><a href={maps} target="_blank" rel="noopener noreferrer">Rua Vereador Alberto Geron, 137<br/>Bortot · Pato Branco – PR <ArrowUpRight size={14}/></a></div><div className="wrap footer-bottom"><span>© 2026 Auto Mecânica Vans</span><span>Proposta de site para apresentação comercial · Criação Felipe</span></div></footer>
    <script dangerouslySetInnerHTML={{__html: `(()=>{const form=document.getElementById('whatsapp-request');if(!form)return;const button=document.getElementById('prepare-request');const status=document.getElementById('request-status');const preview=document.getElementById('request-preview');function prepare(event){event.preventDefault();if(!form.reportValidity())return;const get=name=>form.elements.namedItem(name).value.trim();const message=['Olá, Auto Mecânica Vans! Gostaria de consultar um atendimento.','Nome: '+get('customer'),'Meu WhatsApp: '+get('phone'),'Veículo: '+get('vehicle'),'Serviço: '+get('service'),get('notes')?'Observação: '+get('notes'):''].filter(Boolean).join('\\n');const destination=form.dataset.whatsapp||'';if(/^55[1-9][0-9]{9,10}$/.test(destination)){window.location.assign('https://wa.me/'+destination+'?text='+encodeURIComponent(message));return;}preview.textContent=message;preview.hidden=false;status.textContent='Mensagem preparada abaixo. Demonstração: nenhum dado foi enviado. O direcionamento ao WhatsApp será ativado após a confirmação do número da oficina.';}button.addEventListener('click',prepare);form.addEventListener('submit',prepare);form.addEventListener('input',()=>{preview.hidden=true;status.textContent='Formulário demonstrativo para direcionamento ao WhatsApp. Nenhum dado é enviado.';});})();`}}/>
    <div className="mobile-bar"><a href={maps} target="_blank" rel="noopener noreferrer"><MapPin size={19}/> Como chegar</a><a href={phone}><Phone size={18}/> Ligar para a oficina</a></div>
  </>;
}
